---
version: '2.2'
services:
  mc:
    image: eclipsetitan:7.1.1
    build: ..
    container_name: mc
    hostname: mc
    volumes:
      - ./test_in_container.conf:/home/titan/test_in_container.conf
    entrypoint: ['/bin/sh', '-c']
    command: ['(sleep 3; echo cmtc mtc; sleep 1; echo smtc; sleep 15) | mctr_cli /home/titan/test_in_container.conf']
    tty: true
    networks:
      test:
        ipv4_address: 192.168.127.99
    mac_address: "02:02:c0:a8:7f:63"
  mtc:
    build: .
    container_name: mtc
    hostname: mtc
    command: ["mc", "33333"]
    networks:
      test:
        ipv4_address: 192.168.127.100
    mac_address: "02:02:c0:a8:7f:64"
    cap_add:
      - NET_ADMIN
    depends_on:
      - mc
      - ptc1
      - ptc2
  ptc1:
    build: .
    container_name: ptc1
    hostname: ptc1
    command: ["mc", "33333"]
    networks:
      test:
        ipv4_address: 192.168.127.101
    mac_address: "02:02:c0:a8:7f:65"
    cap_add:
      - NET_ADMIN
    depends_on:
      - mc
  ptc2:
    build: .
    container_name: ptc2
    hostname: ptc2
    command: ["mc", "33333"]
    networks:
      test:
        ipv4_address: 192.168.127.102
    mac_address: "02:02:c0:a8:7f:66"
    cap_add:
      - NET_ADMIN
    depends_on:
      - mc
networks:
  test:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.127.0/24
          gateway: 192.168.127.1
